apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: deploypostgres.postgres.example.com
spec:
  group: postgres.example.com
  names:
    kind: DeployPostgres
    listKind: DeployPostgresList
    plural: deploypostgres
    singular: deploypostgres
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: DeployPostgres is the Schema for the deploypostgres API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: DeployPostgresSpec defines the desired state of DeployPostgres
          properties:
            size:
              format: int32
              type: integer
      #      status:
       #       format: string
        #      type: string
          required:
          - size
         # - status
          type: object
        status:
          description: Status defines the observed state of DeployPostgres
          properties:
            status:
              description: status
              items:
                type: string
          required:
          - status
          type: object
         #status:
          #description: DeployPostgresStatus defines the observed state of DeployPostgres
          #type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
