apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-go
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-go
  template:
    metadata:
      labels:
        name: postgres-go
    spec:
      serviceAccountName: postgres-go
      containers:
        - name: postgres-go
          # Replace this with the built image name
          image: quay.io/prasanth17/postgres-go:v0.0.1
          command:
          - postgres-go
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "postgres-go"
